server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://39.107.114.231:3306/mine?allowMultiQueries=true
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver  